# Generated by Django 4.2.7 on 2025-05-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_rename_timestamp_filledform_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledform',
            name='form_id',
            field=models.CharField(max_length=32),
        ),
    ]
